# -*- coding: utf-8 -*-
"""Week 3 Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5CkzTYVlB-gHzbkx4oj8GL4InnGybd0
"""

import pandas as pd
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
print("California Housing Data from CSV:")
print(data.head())

import pandas as pd
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
print("Missing Values in Dataset:")
print(data.isnull().sum())
data = data.drop_duplicates()
data.fillna(data.mean(numeric_only=True), inplace=True)
for column in data.select_dtypes(include='object'):
    data[column].fillna(data[column].mode()[0], inplace=True)
print("\nMissing Values After Cleaning:")
print(data.isnull().sum())
print("\nCleaned Dataset:")
print(data.head())

import pandas as pd
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
print("Dataset Preview:")
print(data.head())
print("\nDataset Information:")
print(data.info())
print("\nStatistical Summary:")
print(data.describe())
print("\nAverage Median Income:", data['median_income'].mean())
print("Average Median House Value:", data['median_house_value'].mean())
print("Average Total Rooms:", data['total_rooms'].mean())
print("Average Population:", data['population'].mean())
housing_age_analysis = data.groupby('housing_median_age').mean(numeric_only=True)
print("\nAverage Housing Parameters by Median Age:")
print(housing_age_analysis)

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
plt.figure(figsize=(10, 8))
plt.scatter(data['longitude'], data['latitude'], alpha=0.4,
            c=data['median_house_value'], cmap='jet', s=data['population']/100)
plt.title("California Housing: Longitude vs Latitude (Colored by Median House Value, Sized by Population)")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
cbar = plt.colorbar()
cbar.set_label('Median House Value')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
plt.figure(figsize=(7,5))
plt.hist(data['median_income'], bins=20, color='orange', edgecolor='black')
plt.title("Median Income Distribution")
plt.xlabel("Median Income")
plt.ylabel("Frequency")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
plt.figure(figsize=(7,5))
plt.scatter(data['total_rooms'], data['total_bedrooms'], color='green', alpha=0.5)
plt.title("Relationship Between Total Rooms and Total Bedrooms")
plt.xlabel("Total Rooms")
plt.ylabel("Total Bedrooms")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
housing_age_count = data['housing_median_age'].value_counts()
plt.figure(figsize=(8,8))
plt.pie(housing_age_count, labels=housing_age_count.index, autopct='%1.1f%%', startangle=90)
plt.title("Distribution by Housing Median Age")
plt.show()